language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install:
    - composer install
script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml
after_success:
    - travis_retry php vendor/bin/coveralls -v
